[package]
name = "ic-response-verification"
version = "0.0.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
console_error_panic_hook = "0.1.7"
lazy-regex = "2.3.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4.5"
wasm-bindgen = "0.2.83"
