---
commitizen:
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.2.1
  version_files:
  - packages/ic-response-verification/Cargo.toml:version
  - packages/ic-response-verification-tests/Cargo.toml:version
  - packages/ic-response-verification-tests/package.json:version
  - packages/ic-response-verification-test-utils/Cargo.toml:version
  - packages/ic-response-verification-wasm/package.json:version
  - packages/ic-response-verification-wasm/Cargo.toml:version
