---
commitizen:
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 2.5.0
  version_files:
  - Cargo.toml
  - packages/certificate-verification-js/package.json:version
  - packages/ic-certification-testing-wasm/package.json:version
  - packages/ic-response-verification-tests/package.json:version
  - packages/ic-response-verification-wasm/package.json:version
