packages:
  - examples/certification/certified-counter/src/frontend
  - examples/http-certification/assets/src/frontend
  - examples/http-certification/assets/src/tests
  - examples/http-certification/custom-assets/src/frontend
  - examples/http-certification/custom-assets/src/tests
  - examples/http-certification/json-api/src/tests
  - examples/http-certification/skip-certification/src/tests
  - examples/http-certification/upgrade-to-update-call/src/tests
  - packages/certificate-verification-js
  - packages/ic-certification-testing-wasm
  - packages/ic-response-verification-wasm
  - packages/ic-response-verification-tests/src/frontend
  - packages/ic-response-verification-tests/src/wasm-tests

onlyBuiltDependencies:
  - '@dfinity/pic'
  - esbuild
