packages:
  - 'packages/certificate-verification-js'
  - 'packages/ic-certification-testing-wasm'
  - 'packages/ic-response-verification-wasm'
  - 'packages/ic-response-verification-tests'
  - 'packages/ic-response-verification-tests/dfx-project'
  - 'examples/certification/certified-counter'
  - 'examples/response-verification/nodejs'
  - 'examples/response-verification/web'
  - 'examples/http-certification/assets/src/frontend'
  - 'examples/http-certification/custom-assets/src/frontend'
  - 'examples/http-certification/json-api/src/tests'
