packages:
  - 'packages/certificate-verification-js'
  - 'packages/ic-certification-testing-wasm'
  - 'packages/ic-response-verification-wasm'
  - 'packages/ic-response-verification-tests/wasm-tests'
  - 'packages/ic-response-verification-tests/dfx-project'
  - 'examples/certified-counter'
  - 'examples/nodejs'
  - 'examples/service-worker'
  - 'examples/web'
