[package]
name = "http_certification_upgrade_to_update_call_rust_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-http-certification.workspace = true
