[package]
name = "ic-response-verification"
description = "Client side response verification for the Internet Computer"
version = "1.0.2"
authors = ["DFINITY Stiftung"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ic-response-verification"
homepage = "https://github.com/dfinity/response-verification#readme"
repository = "https://github.com/dfinity/response-verification"
categories = ["api-bindings", "authentication", "cryptography", "wasm"]
keywords = ["internet-computer", "icp", "dfinity", "response", "verification"]
edition = "2021"
include = ["src", "Cargo.toml", "README.md"]

[features]
debug = ["log/max_level_trace", "log/release_max_level_trace"]
js = ["dep:wasm-bindgen", "dep:js-sys"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.21"
nom = "7.1"
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
thiserror = "1.0"
sha2 = "0.10"
http = "0.2"
ic-certification = { version = "0.25", default_features = false }
ic-representation-independent-hash =  { path = "../ic-representation-independent-hash", version = "1.0.2" }
ic-cbor = { path = "../ic-cbor", version = "1.0.2"}
ic-certificate-verification ={ path = "../ic-certificate-verification", version = "1.0.2" }
flate2 = "1.0"
leb128 = "0.2"
candid = "0.9"
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
hex = "0.4"
urlencoding = "2.1.3"

[dev-dependencies]
serde_cbor = "0.11"
wasm-bindgen-test = "0.3"
ic-certification = "0.25"
candid = "0.9"
serde = "1.0"
ic-response-verification-test-utils = { path = "../ic-response-verification-test-utils" }
ic-crypto-tree-hash = { git = "https://github.com/dfinity/ic", rev = "23a96f71e4ff434f1aaae04eb1d9e9ab36d663f0" }
ic-types = { git = "https://github.com/dfinity/ic", rev = "23a96f71e4ff434f1aaae04eb1d9e9ab36d663f0" }
ic-certified-map = "0.4"
rstest = "0.18"
ic-certification-testing = { path = "../ic-certification-testing" }
