[package]
name = "ic-response-verification-wasm"
description = "WASM version of client side response verification for the Internet Computer"
version = "1.0.2"
authors = ["DFINITY Stiftung"]
license = "Apache-2.0"
edition = "2021"
include = ["src", "Cargo.toml", "README.md"]

[features]
debug = ["ic-response-verification/debug"]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
ic-response-verification = { path = "../ic-response-verification", features = ["js"] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
wasm-bindgen = "0.2"
log = "0.4"
wasm-bindgen-console-logger = "0.1"

[dev-dependencies]
base64 = "0.21"
wasm-bindgen-test = "0.3"
ic-response-verification-test-utils = { path = "../ic-response-verification-test-utils" }
