[package]
name = "ic-response-verification-wasm"
description = "WASM version of client side response verification for the Internet Computer"
version = "0.2.1"
authors = ["DFINITY Stiftung"]
license = "Apache-2.0"
edition = "2021"
include = ["src", "Cargo.toml", "README.md"]

[features]
debug = ["dep:log", "dep:wasm-bindgen-console-logger", "ic-response-verification/debug"]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
ic-response-verification = { path = "../ic-response-verification", features = ["js"] }
console_error_panic_hook = "0.1.7"
js-sys = "0.3"
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"
log = { version = "0.4.17", optional = true }
wasm-bindgen-console-logger = { version = "0.1.1", optional = true }

[dev-dependencies]
base64 = "0.21.0"
wasm-bindgen-test = "0.3"
ic-response-verification-test-utils = { path = "../ic-response-verification-test-utils" }
