[package]
name = "representation-independent-hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic_crypto_sha = { git = "https://github.com/dfinity/ic", package = "ic-crypto-sha" }
