[package]
name = "ic-response-verification-tests"
version = "0.2.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
http = "0.2.8"
ic-agent = "0.23.1"
ic-utils = "0.23.1"
tokio = { version = "1.24.2", features = ["full"] }
ic-response-verification = { path = "../ic-response-verification", features = ["debug"] }
anyhow = "1.0.68"
