[package]
name = "ic-response-verification-tests"
version = "1.2.0"
edition = "2021"

[dependencies]
hex = "0.4"
http = "0.2"
ic-agent = "0.26.1"
ic-utils = "0.26.1"
tokio = { version = "1.24", features = ["full"] }
ic-response-verification = { path = "../ic-response-verification", features = [
    "debug",
] }
anyhow = "1.0"
