[package]
name = "ic-response-verification-tests"
version = "0.0.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
http = "0.2.8"
ic-agent = { git = "https://github.com/dfinity/agent-rs", branch = "nathan/add-certificate-version-to-http-canister-interface" }
ic-utils = { git = "https://github.com/dfinity/agent-rs", branch = "nathan/add-certificate-version-to-http-canister-interface" } 
tokio = { version = "1.24.2", features = ["full"] }
ic-response-verification = { path = "../ic-response-verification", features = ["debug"] }
anyhow = "1.0.68"
