[package]
name = "ic-response-verification-tests"
version = "1.0.2"
edition = "2021"

[dependencies]
hex = "0.4.3"
http = "0.2.8"
ic-agent = { git = "https://github.com/dfinity/agent-rs.git" }
ic-utils = { git = "https://github.com/dfinity/agent-rs.git" }
tokio = { version = "1.24.2", features = ["full"] }
ic-response-verification = { path = "../ic-response-verification", features = ["debug"] }
anyhow = "1.0.68"
