[package]
name = "ic-http-certification"
description = "Certification for HTTP responses for the Internet Computer"
readme = "README.md"
documentation = "https://docs.rs/ic-http-certification"
categories = ["api-bindings", "data-structures", "algorithms", "cryptography::cryptocurrencies"]
keywords = ["internet-computer", "agent", "utility", "icp", "dfinity"]
include = ["src", "Cargo.toml", "LICENSE", "README.md"]

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
candid.workspace = true
serde.workspace = true
http.workspace = true
urlencoding.workspace = true
ic-representation-independent-hash.workspace = true
ic-certification = { workspace = true, features = ["serde"] }
thiserror.workspace = true
base64.workspace = true
serde_cbor.workspace = true

[dev-dependencies]
rstest.workspace = true
rstest_reuse.workspace = true
hex.workspace = true
assert_matches.workspace = true
