[package]
name = "ic-representation-independent-hash"
description = "A library for computing representation-independent hashes as described in the Internet Computer interface specification."
readme = "README.md"
documentation = "https://docs.rs/ic-representation-independent-hash"
categories = ["cryptography", "hash"]
keywords = ["icp", "dfinity", "representation", "independent", "hash"]
include = ["src", "Cargo.toml", "README.md"]

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
sha2.workspace = true
leb128.workspace = true

[dev-dependencies]
hex.workspace = true
