[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
candid = "0.8.2"
hex = "0.4.3"
ic-cdk = "0.6.0"
ic-cdk-macros = "0.6.0"
ic-certified-map = "0.3.4"
serde = "1.0.164"
serde_cbor = "0.11.2"
sha2 = "0.10"
