[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-response-verification.workspace = true
ic-http-certification.workspace = true
candid.workspace = true
hex.workspace = true
serde.workspace = true
serde_bytes.workspace = true
