[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-response-verification = { path = "../../packages/ic-response-verification" }
candid = "0.8.4"
hex = "0.4.3"
serde = "1.0.147"
serde_bytes = "0.11.7"
