[package]
name = "ic-certification-testing-wasm"
description = "Utilities for testing applications that work with Internet Computer certification"
version = "1.1.0"
authors = ["DFINITY Stiftung"]
license = "Apache-2.0"
edition = "2021"
include = ["src", "Cargo.toml", "README.md"]

[features]
debug = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
wasm-bindgen-console-logger = "0.1"
serde-wasm-bindgen = "0.5"
ic-certification-testing = { path = "../ic-certification-testing" }
log = "0.4"
ic-types = { git = "https://github.com/dfinity/ic", rev = "6e3bb8100e7724a8ec53dac26faa3426378a6953" }
