[package]
name = "ic-asset-certification"
description = "Certification for static assets served over HTTP on the Internet Computer"
readme = "README.md"
documentation = "https://docs.rs/ic-asset-certification"
categories = ["api-bindings", "data-structures", "algorithms", "cryptography::cryptocurrencies"]
keywords = ["internet-computer", "agent", "utility", "icp", "dfinity"]
include = ["src", "Cargo.toml", "LICENSE", "README.md"]

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
http.workspace = true
ic-certification.workspace = true
ic-http-certification.workspace = true
thiserror.workspace = true
globset = "0.4"
regex.workspace = true

[dev-dependencies]
rstest.workspace = true
assert_matches.workspace = true
