name: Check commit messages

on:
  pull_request:

jobs:
  check_commit_messages:
    name: Check Commit Messages
    uses: dfinity/ci-tools/.github/workflows/check-commit-messages.yaml@nathan/main
    with:
      starting_commit: 'ac8f90b7c45e13e240d6c01a43d191b99f1aec4a'
