name: Check commit messages

on:
  pull_request:
    branches:
      - main

jobs:
  check_commit_messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Check Commit Messages
        run: cz check --rev-range 4b3de72e9b2a1ea5b700851c25db6f42cb55e8fa..HEAD
