name: commitizen

on:
  pull_request:

jobs:
  check_commit_messages:
    name: check_commit_messages:required
    uses: dfinity/ci-tools/.github/workflows/check-commit-messages.yaml@main
    with:
      target_branch: 'main'

  check_pr_title:
    name: check_pr_title:required
    uses: dfinity/ci-tools/.github/workflows/check-pr-title.yaml@main
