name: Create Release PR

on: workflow_dispatch

jobs:
  bump_version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Bump Version
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: RELEASE_NOTES.md
          commit: false
          push: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Bumping to version ${{ steps.cz.outputs.version }}"

      - name: Update Cargo.lock
        run: cargo build -p ic-response-verification

      - name: Update package-lock.json
        run: npm i --package-lock-only
        working-directory: packages/ic-response-verification-wasm

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Release ${{ steps.cz.outputs.version }}"
          body: |
            After merging this PR, tag the merge commit with:
            ```shell
              git tag ${{ steps.cz.outputs.version }}
              git push origin ${{ steps.cz.outputs.version }}
            ```
          commit-message: "chore: release ${{ steps.cz.outputs.version }}"
          branch: "release/${{ steps.cz.outputs.version }}"
          team-reviewers: "@dfinity/trust"
          add-paths: |
            .cz.yaml
            CHANGELOG.md
            Cargo.lock
            packages/ic-response-verification/Cargo.toml
            packages/ic-response-verification-tests/Cargo.toml
            packages/ic-response-verification-test-utils/Cargo.toml
            packages/ic-response-verification-wasm/package.json
            packages/ic-response-verification-wasm/package-lock.json
            packages/ic-response-verification-wasm/Cargo.toml
