name: e2e Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'

jobs:
  e2e_tests:
    name: e2e Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-pnpm

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Setup e2e Deps Cache
        uses: actions/cache@v3
        with:
          path: tmp/
          key: ${{ runner.os }}-tmp

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: e2e tests
        run: ./scripts/e2e.sh
