name: Update changelog

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Check Commit Messages
        run: cz check --rev-range c8ecbc19b8c4a482e55907d37554d66f2f2f9a8f..HEAD

      - name: Update Changelog
        run: cz changelog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Update changelog'
          commit-message: 'chore: update changelog'
          branch: 'chore/update-changelog'
          branch-suffix: 'short-commit-hash'
          add-paths: |
            CHANGELOG.md
