name: generate_changelog

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    uses: dfinity/ci-tools/.github/workflows/generate-changelog.yaml@main
    with:
      auto_merge: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
