name: 'Setup DFX'
description: Setup DFX

runs:
  using: 'composite'
  steps:
    - name: Install dfx
      uses: dfinity/setup-dfx@main

    - name: Run DFX
      shell: bash
      run: |
        dfx start --clean --background
